---
# handlers file for haproxy

- name: restart haproxy
  service: name={{ haproxy_service_name }} state=restarted
  tags: haproxy

- name: reload haproxy
  service: name={{ haproxy_service_name }} state=reloaded
  tags: haproxy
