---
# handlers file for haproxy

- name: restart haproxy
  become: yes
  service:
    name: "{{ haproxy_service_name }}"
    state: restarted
  tags:
    - haproxy

- name: reload haproxy
  become: yes
  service:
    name: "{{ haproxy_service_name }}"
    state: reloaded
  tags:
    - haproxy
